server:
  port: 8081

spring:
  application:
    name: AUTH-SERVICE

  datasource:
    url: jdbc:mysql://mysql:3306/auth_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://service-registry:8761/eureka/

jwt:
  secret: mysecretkeymysecretkeymysecretkeymysecretkey
  expiration: 86400000