spring:
  main:
    web-application-type: reactive

  application:
    name: API-GATEWAY

  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true

          routes:
            - id: auth-service
              uri: lb://AUTH-SERVICE
              predicates:
                - Path=/api/auth/**

            - id: order-service
              uri: lb://ORDER-SERVICE
              predicates:
                - Path=/api/orders/**

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://service-registry:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"

jwt:
  secret: mysecretkeymysecretkeymysecretkeymysecretkey